language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings_tests

node_js:  
  - "9.11.2"

before_script:
  - psql -c 'create database  greetings_tests;' -U postgres
  - psql -U postgres -d greeting_tests -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
